export type Presets = {
  label: string
  value: string
}[]

export type MenuType = {
  menus: string[]
  presets: Presets
  operators: string[]
  greekLetters: string[]
  inequation: string[]
  calculus: string[]
  arrows: string[]
  trigonometric: string[]
}

/** 编辑器按钮配置 */
export const menusConfig: MenuType = {
  menus: [
    'presets',
    'operators',
    'greekLetters',
    'inequation',
    'calculus',
    'arrows',
    'Trigonometric',
  ],
  presets: [
    {
      label: '勾股定理',
      value: 'a^2+b^2=c^2',
    },
    {
      label: '双曲线',
      value: '\\frac{x^2}{a^2}-\\frac{y^2}{b^2}=1',
    },
    {
      label: '正弦',
      value:
        '\\sin \\alpha + \\sin \\beta =2 \\sin \\frac{\\alpha + \\beta}{2}\\cos \\frac{\\alpha - \\beta}{2}',
    },
    {
      label: '正切',
      value: '\\tan(x + y) = \\frac{\\tan x + \\tan y}{1 - \\tan x\\tan y}',
    },
    {
      label: '定积分',
      value: '\\int_a^b f(x) dx = F(b) - F(a)',
    },
    {
      label: '初等函数',
      value: "\\left( \\sin x\\right) '=\\cos x",
    },
  ],
  operators: [
    '+',
    '-',
    '\\pm',
    '\\mp',
    '\\times',
    '\\div',
    '\\ast',
    '\\cdot',
    '\\cap',
    '\\cup',
    '\\aleph',
    '\\Re',
    '\\top',
    '\\bot',
    '\\infty',
    '\\partial',
    '\\forall',
    '\\exists',
    '\\neg',
    '\\because',
    '\\therefore',
    '\\varnothing',
    '\\frac{b}{a}',
    '\\circ',
    '\\bullet',
    '\\prime',
    '\\triangle',
    '\\angle',
    '\\surd',
    '\\barwedge',
    '\\veebar',
    '\\odot',
    '\\oplus',
    '\\otimes',
    '\\oslash',
    '\\circledcirc',
    '\\boxdot',
    '\\bigtriangledown',
    '\\dagger',
    '\\diamond',
    '\\star',
    '\\triangleleft',
    '\\triangleright',
  ],
  greekLetters: [
    '\\alpha',
    '\\beta',
    '\\gamma',
    '\\delta',
    '\\epsilon',
    '\\zeta',
    '\\eta',
    '\\theta',
    '\\iota',
    '\\kappa',
    '\\lambda',
    '\\mu',
    '\\nu',
    '\\xi',
    '\\omicron',
    '\\pi',
    '\\rho',
    '\\sigma',
    '\\tau',
    '\\upsilon',
    '\\phi',
    '\\chi',
    '\\psi',
    '\\omega',
    '\\varepsilon',
    '\\vartheta',
    '\\varpi',
    '\\varrho',
    '\\varsigma',
    '\\varphi',
    '\\Gamma',
    '\\Delta',
    '\\Theta',
    '\\Lambda',
    '\\Xi',
    '\\Pi',
    '\\Sigma',
    '\\Upsilon',
    '\\Phi',
    '\\Psi',
    '\\Omega',
  ],
  inequation: [
    '\\leq',
    '\\geq',
    '\\prec',
    '\\succ',
    '\\preceq',
    '\\succeq',
    '\\ll',
    '\\gg',
    '\\equiv',
    '\\sim',
    '\\simeq',
    '\\asymp',
    '\\approx',
    '\\ne',
    '\\subset',
    '\\supset',
    '\\subseteq',
    '\\supseteq',
    '\\nsubseteq',
    '\\nsupseteq',
    '\\in',
    '\\ni',
    '\\notin',
    '\\vec{a}',
    '\\bar{a}',
    '\\tilde{a}',
    '\\dot{a}',
    '\\ddot{a}',
    '\\hat{a}',
    '\\overleftarrow{ab}',
    '\\overline{ab}',
    '\\overrightarrow{ab}',
    '\\underline{ab}',
    '\\overbrace{ab}',
    '\\underbrace{ab}',
  ],
  calculus: [
    'x_{a}',
    'x^{b}',
    'x_{a}^{b}',
    '\\bar{x}',
    '\\tilde{x}',
    '\\sqrt{x}',
    '\\sqrt[n]{x}',
    '\\bigcap_{a}^{b}',
    '\\bigcup_{a}^{b}',
    '\\prod_{a}^{b}',
    '\\coprod_{a}^{b}',
    '\\left( x  \\right)',
    '\\left[ x  \\right]',
    '\\left \\{ x  \\right \\}',
    '\\left| x  \\right|',
    '\\int_{a}^{b}',
    '\\oint_{a}^{b}',
    '\\sum_{a}^{b}{x}',
    '\\lim_{a  \\rightarrow b}{x}',
    '\\begin{pmatrix}a&b\\\\c&d\\\\ \\end{pmatrix}',
    '\\begin{bmatrix}a&b\\\\c&d\\\\ \\end{bmatrix}',
    '\\begin{Bmatrix}a&b\\\\c&d\\\\ \\end{Bmatrix}',
    '\\begin{vmatrix}a&b\\\\c&d\\\\ \\end{vmatrix}',
    '\\frac{dy}{dx}|_{t=0}',
  ],
  arrows: [
    '\\leftarrow',
    '\\rightarrow',
    '\\leftrightarrow',
    '\\Leftarrow',
    '\\Rightarrow',
    '\\Leftrightarrow',
    '\\uparrow',
    '\\downarrow',
    '\\updownarrow',
    '\\Uparrow',
    '\\Downarrow',
    '\\Updownarrow',
  ],
  trigonometric: [
    '\\sin \\theta',
    '\\cos \\theta',
    '\\tan \\theta',
    '\\csc \\theta',
    '\\sec \\theta',
    '\\cot \\theta',
  ],
}
